---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--force --verbose'

images:
  base_image:
    name: ghcr.io/ansible-community/community-ee-minimal:latest

dependencies:
  python: requirements.txt
  galaxy: requirements.yml

additional_build_files:
   - src: ansible.cfg
     dest: configs

additional_build_steps:
  prepend_builder: |
    RUN pip3 install --upgrade pip setuptools
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
  append_final: |
    RUN cd /usr/local/bin && \
        curl -O https://mirror.openshift.com/pub/rhacs/assets/4.1.2/bin/linux/roxctl && \
        chmod +x /usr/local/bin/roxctl
